version: '3.8'

services:
  # FastAPI Application (Local Development)
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: perfect-po-api-local
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=local
      - DEBUG=true
      - MONGODB_URI=mongodb://mongodb:27017/perfect_po_dev
      - REDIS_URL=redis://redis:6379
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - KEEPA_API_KEY=${KEEPA_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-local_dev_secret_key}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES:-10080}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - .:/app  # Mount source code for live reload
    networks:
      - perfect-po-local-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # MongoDB Database (Local Development)
  mongodb:
    image: mongo:7.0
    container_name: perfect-po-mongodb-local
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-dev_password}
      - MONGO_INITDB_DATABASE=perfect_po_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_local_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - perfect-po-local-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Redis Cache (Local Development)
  redis:
    image: redis:7.2-alpine
    container_name: perfect-po-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_local_data:/data
    networks:
      - perfect-po-local-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'

  # Nginx Reverse Proxy (Local Development - HTTP only)
  nginx:
    image: nginx:alpine
    container_name: perfect-po-nginx-local
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - perfect-po-local-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

  # MongoDB Express (Local Development - for easy DB management)
  mongo-express:
    image: mongo-express:latest
    container_name: perfect-po-mongo-express-local
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-dev_password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-dev_password}@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-admin123}
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - perfect-po-local-network

volumes:
  mongodb_local_data:
    driver: local
  redis_local_data:
    driver: local

networks:
  perfect-po-local-network:
    driver: bridge
