version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/perfect_po_db
      - DEBUG=true
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - perfect-po-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=perfect_po_db
    volumes:
      - mongo_data:/data/db
    networks:
      - perfect-po-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - perfect-po-network

volumes:
  mongo_data:

networks:
  perfect-po-network:
    driver: bridge

