version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    networks:
      - perfect-po-network

# MongoDB and Mongo Express removed - using remote MongoDB from .env file

networks:
  perfect-po-network:
    driver: bridge


